server:
  port: 8082
  servlet:
    context-path: /energy



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/application?characterEncoding=utf-8
    username: root
    password: Lxcc@2018

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


#logging:
#  pattern:
#    console: "%d -%msg%n"
#    file:  "%d -%msg%n"
#  file:
#    name: /Users/chrislee/Documents/log/four.log
#    path: /Users/chrislee/Documents/log
#  level:
#    com.example.demo.LogTest.LogTest: debug


#todo:
#  date: "3月26日"
#  thing: ${todo.date} + 去看电影